-- =====================================================
-- UPENDO CHAT SYSTEM - COMPLETE DATABASE SETUP
-- =====================================================
-- This script creates the complete chat and conversation system
-- Ensures message persistence across navigation and refresh
-- =====================================================

-- =====================================================
-- CORE TABLES FOR CHAT SYSTEM
-- =====================================================

-- Profiles table (users)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT,
    photos TEXT[],
    subscription TEXT DEFAULT 'free',
    account_type TEXT DEFAULT 'free',
    is_verified BOOLEAN DEFAULT false,
    last_active_at TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Matches table (conversations between users)
CREATE TABLE IF NOT EXISTS public.matches (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user1_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    user2_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    last_message_at TIMESTAMPTZ,
    CONSTRAINT unique_match UNIQUE(user1_id, user2_id)
);

-- Messages table (individual messages)
CREATE TABLE IF NOT EXISTS public.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id UUID NOT NULL REFERENCES public.matches(id) ON DELETE CASCADE,
    sender_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    type TEXT DEFAULT 'text',
    is_read BOOLEAN DEFAULT false,
    is_edited BOOLEAN DEFAULT false,
    is_deleted BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- =====================================================
-- INDEXES FOR PERFORMANCE
-- =====================================================

-- Index for fast message retrieval by match
CREATE INDEX IF NOT EXISTS idx_messages_match_id ON public.messages(match_id);
CREATE INDEX IF NOT EXISTS idx_messages_created_at ON public.messages(created_at);
CREATE INDEX IF NOT EXISTS idx_messages_match_created ON public.messages(match_id, created_at DESC);

-- Index for match queries
CREATE INDEX IF NOT EXISTS idx_matches_user1 ON public.matches(user1_id);
CREATE INDEX IF NOT EXISTS idx_matches_user2 ON public.matches(user2_id);
CREATE INDEX IF NOT EXISTS idx_matches_last_message ON public.matches(last_message_at DESC);

-- Index for sender queries
CREATE INDEX IF NOT EXISTS idx_messages_sender ON public.messages(sender_id);

-- =====================================================
-- TRIGGERS FOR AUTOMATIC UPDATES
-- =====================================================

-- Trigger to update match's last_message_at when new message is sent
CREATE OR REPLACE FUNCTION update_match_last_message()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE public.matches 
    SET last_message_at = NEW.created_at,
        updated_at = NOW()
    WHERE id = NEW.match_id;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_match_last_message
    AFTER INSERT ON public.messages
    FOR EACH ROW
    EXECUTE FUNCTION update_match_last_message();

-- Trigger to update sender's last_message_sent_at
CREATE OR REPLACE FUNCTION update_sender_last_message()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE public.profiles 
    SET last_message_sent_at = NEW.created_at
    WHERE id = NEW.sender_id;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_sender_last_message
    AFTER INSERT ON public.messages
    FOR EACH ROW
    EXECUTE FUNCTION update_sender_last_message();

-- =====================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- =====================================================

-- Enable RLS
ALTER TABLE public.matches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

-- Matches policies
CREATE POLICY "Users can view their own matches" ON public.matches
    FOR SELECT USING (
        auth.uid() = user1_id OR auth.uid() = user2_id
    );

CREATE POLICY "Users can insert matches" ON public.matches
    FOR INSERT WITH CHECK (
        auth.uid() = user1_id OR auth.uid() = user2_id
    );

-- Messages policies
CREATE POLICY "Users can view messages from their matches" ON public.messages
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM public.matches 
            WHERE matches.id = messages.match_id 
            AND (matches.user1_id = auth.uid() OR matches.user2_id = auth.uid())
        )
    );

CREATE POLICY "Users can send messages to their matches" ON public.messages
    FOR INSERT WITH CHECK (
        sender_id = auth.uid() AND
        EXISTS (
            SELECT 1 FROM public.matches 
            WHERE matches.id = match_id 
            AND (matches.user1_id = auth.uid() OR matches.user2_id = auth.uid())
        )
    );

CREATE POLICY "Users can update their own messages" ON public.messages
    FOR UPDATE USING (sender_id = auth.uid());

-- =====================================================
-- STORED PROCEDURES FOR CHAT OPERATIONS
-- =====================================================

-- Get all conversations for a user with last message
CREATE OR REPLACE FUNCTION get_user_conversations(user_uuid UUID)
RETURNS TABLE (
    match_id UUID,
    other_user_id UUID,
    other_user_name TEXT,
    other_user_photos TEXT[],
    last_message_content TEXT,
    last_message_time TIMESTAMPTZ,
    last_message_sender_id UUID,
    unread_count BIGINT,
    created_at TIMESTAMPTZ
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        m.id as match_id,
        CASE 
            WHEN m.user1_id = user_uuid THEN m.user2_id 
            ELSE m.user1_id 
        END as other_user_id,
        CASE 
            WHEN m.user1_id = user_uuid THEN p2.name 
            ELSE p1.name 
        END as other_user_name,
        CASE 
            WHEN m.user1_id = user_uuid THEN p2.photos 
            ELSE p1.photos 
        END as other_user_photos,
        last_msg.content as last_message_content,
        last_msg.created_at as last_message_time,
        last_msg.sender_id as last_message_sender_id,
        (
            SELECT COUNT(*) 
            FROM public.messages msg 
            WHERE msg.match_id = m.id 
            AND msg.sender_id != user_uuid 
            AND msg.is_read = false
        ) as unread_count,
        m.created_at
    FROM public.matches m
    LEFT JOIN public.profiles p1 ON m.user1_id = p1.id
    LEFT JOIN public.profiles p2 ON m.user2_id = p2.id
    LEFT JOIN LATERAL (
        SELECT content, created_at, sender_id
        FROM public.messages 
        WHERE match_id = m.id 
        ORDER BY created_at DESC 
        LIMIT 1
    ) last_msg ON true
    WHERE (m.user1_id = user_uuid OR m.user2_id = user_uuid)
    AND m.last_message_at IS NOT NULL
    ORDER BY m.last_message_at DESC;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Get messages for a specific conversation
CREATE OR REPLACE FUNCTION get_conversation_messages(match_uuid UUID, user_uuid UUID)
RETURNS TABLE (
    message_id BIGINT,
    sender_id UUID,
    sender_name TEXT,
    content TEXT,
    type TEXT,
    is_read BOOLEAN,
    is_edited BOOLEAN,
    created_at TIMESTAMPTZ
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        msg.id as message_id,
        msg.sender_id,
        p.name as sender_name,
        msg.content,
        msg.type,
        msg.is_read,
        msg.is_edited,
        msg.created_at
    FROM public.messages msg
    JOIN public.profiles p ON msg.sender_id = p.id
    WHERE msg.match_id = match_uuid
    AND EXISTS (
        SELECT 1 FROM public.matches 
        WHERE id = match_uuid 
        AND (user1_id = user_uuid OR user2_id = user_uuid)
    )
    ORDER BY msg.created_at ASC;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Send a message and update conversation
CREATE OR REPLACE FUNCTION send_message(
    p_match_id UUID,
    p_sender_id UUID,
    p_content TEXT,
    p_type TEXT DEFAULT 'text'
)
RETURNS BIGINT AS $$
DECLARE
    new_message_id BIGINT;
BEGIN
    -- Verify the sender is part of the match
    IF NOT EXISTS (
        SELECT 1 FROM public.matches 
        WHERE id = p_match_id 
        AND (user1_id = p_sender_id OR user2_id = p_sender_id)
    ) THEN
        RAISE EXCEPTION 'User is not part of this conversation';
    END IF;

    -- Insert the message
    INSERT INTO public.messages (match_id, sender_id, content, type)
    VALUES (p_match_id, p_sender_id, p_content, p_type)
    RETURNING id INTO new_message_id;

    RETURN new_message_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Mark messages as read
CREATE OR REPLACE FUNCTION mark_messages_as_read(
    p_match_id UUID,
    p_user_id UUID
)
RETURNS VOID AS $$
BEGIN
    UPDATE public.messages 
    SET is_read = true
    WHERE match_id = p_match_id 
    AND sender_id != p_user_id 
    AND is_read = false;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Get conversation stats
CREATE OR REPLACE FUNCTION get_conversation_stats(
    p_match_id UUID,
    p_user_id UUID
)
RETURNS TABLE (
    total_messages BIGINT,
    unread_count BIGINT,
    last_message_time TIMESTAMPTZ,
    other_user_last_active TIMESTAMPTZ
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        (SELECT COUNT(*) FROM public.messages WHERE match_id = p_match_id) as total_messages,
        (SELECT COUNT(*) FROM public.messages WHERE match_id = p_match_id AND sender_id != p_user_id AND is_read = false) as unread_count,
        (SELECT MAX(created_at) FROM public.messages WHERE match_id = p_match_id) as last_message_time,
        CASE 
            WHEN m.user1_id = p_user_id THEN p2.last_active_at
            ELSE p1.last_active_at
        END as other_user_last_active
    FROM public.matches m
    LEFT JOIN public.profiles p1 ON m.user1_id = p1.id
    LEFT JOIN public.profiles p2 ON m.user2_id = p2.id
    WHERE m.id = p_match_id
    AND (m.user1_id = p_user_id OR m.user2_id = p_user_id);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =====================================================
-- MIGRATION SCRIPTS FOR EXISTING DATA
-- =====================================================

-- If you need to migrate from old message structure
CREATE OR REPLACE FUNCTION migrate_messages_to_matches()
RETURNS VOID AS $$
BEGIN
    -- This function would handle migrating old message data
    -- to the new structure if needed
    RAISE NOTICE 'Migration function placeholder - implement based on your needs';
END;
$$ LANGUAGE plpgsql;

-- =====================================================
-- TESTING QUERIES
-- =====================================================

-- Test creating a match
/*
INSERT INTO public.matches (user1_id, user2_id) 
VALUES ('user1-uuid', 'user2-uuid') 
RETURNING *;
*/

-- Test sending a message
/*
SELECT send_message(
    'match-uuid',
    'sender-uuid', 
    'Hello, how are you?',
    'text'
);
*/

-- Test getting conversations
/*
SELECT * FROM get_user_conversations('user-uuid');
*/

-- Test getting conversation messages
/*
SELECT * FROM get_conversation_messages('match-uuid', 'user-uuid');
*/

-- Test marking messages as read
/*
SELECT mark_messages_as_read('match-uuid', 'user-uuid');
*/

-- =====================================================
-- PERFORMANCE MONITORING QUERIES
-- =====================================================

-- Check message count per conversation
SELECT match_id, COUNT(*) as message_count 
FROM public.messages 
GROUP BY match_id 
ORDER BY message_count DESC;

-- Check for conversations without recent messages
SELECT m.*, 
       CASE WHEN m.user1_id = 'current-user-uuid' THEN m.user2_id ELSE m.user1_id END as other_user_id
FROM public.matches m
WHERE (m.user1_id = 'current-user-uuid' OR m.user2_id = 'current-user-uuid')
AND (m.last_message_at IS NULL OR m.last_message_at < NOW() - INTERVAL '30 days');

-- Message volume by day
SELECT DATE(created_at) as message_date, COUNT(*) as daily_messages
FROM public.messages 
WHERE created_at > NOW() - INTERVAL '30 days'
GROUP BY DATE(created_at)
ORDER BY message_date DESC;