CREATE TABLE public.promo_codes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  duration_days INT NOT NULL,
  type TEXT NOT NULL, -- e.g., 'VIP', 'BOOST'
  created_at TIMESTAMPTZ DEFAULT NOW()
);
