-- Create the dislikes table
CREATE TABLE IF NOT EXISTS dislikes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    disliked_user_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Add a unique constraint to prevent duplicate dislikes (only if table is new)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint 
        WHERE conname = 'unique_dislike' 
        AND conrelid = 'dislikes'::regclass
    ) THEN
        ALTER TABLE dislikes
        ADD CONSTRAINT unique_dislike UNIQUE (user_id, disliked_user_id);
    END IF;
END $$;

-- Create indexes for faster queries
CREATE INDEX IF NOT EXISTS idx_dislikes_user_id ON dislikes(user_id);
CREATE INDEX IF NOT EXISTS idx_dislikes_disliked_user_id ON dislikes(disliked_user_id);

-- Enable RLS
ALTER TABLE dislikes ENABLE ROW LEVEL SECURITY;

-- Create RLS policies
CREATE POLICY IF NOT EXISTS "Users can insert their own dislikes"
ON dislikes
FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY IF NOT EXISTS "Users can view their own dislikes"
ON dislikes
FOR SELECT USING (auth.uid() = user_id);