-- =====================================================
-- REFRESH AND NAVIGATION HANDLING SYSTEM
-- UPENDO CHAT PERSISTENCE SCRIPTS
-- =====================================================

-- =====================================================
-- SESSION AND STATE MANAGEMENT
-- =====================================================

-- Create table for tracking user session state
CREATE TABLE IF NOT EXISTS public.user_session_state (
    user_id UUID PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
    last_conversation_id UUID REFERENCES public.matches(id) ON DELETE SET NULL,
    last_message_check_time TIMESTAMPTZ DEFAULT NOW(),
    conversations_viewed_at TIMESTAMPTZ DEFAULT NOW(),
    messages_viewed_at TIMESTAMPTZ DEFAULT NOW(),
    session_start_time TIMESTAMPTZ DEFAULT NOW(),
    session_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create table for conversation read state
CREATE TABLE IF NOT EXISTS public.conversation_read_state (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    match_id UUID NOT NULL REFERENCES public.matches(id) ON DELETE CASCADE,
    last_read_message_id BIGINT REFERENCES public.messages(id) ON DELETE SET NULL,
    last_read_time TIMESTAMPTZ DEFAULT NOW(),
    unread_count INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, match_id)
);

-- Create table for message sync tracking
CREATE TABLE IF NOT EXISTS public.message_sync_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    match_id UUID NOT NULL REFERENCES public.matches(id) ON DELETE CASCADE,
    sync_type TEXT NOT NULL, -- 'full', 'incremental', 'refresh'
    messages_synced INTEGER DEFAULT 0,
    sync_status TEXT DEFAULT 'pending', -- 'pending', 'completed', 'failed'
    sync_start_time TIMESTAMPTZ DEFAULT NOW(),
    sync_end_time TIMESTAMPTZ,
    error_message TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- =====================================================
-- TRIGGERS FOR AUTOMATIC STATE MANAGEMENT
-- =====================================================

-- Trigger to update conversation read state when messages are read
CREATE OR REPLACE FUNCTION update_conversation_read_state()
RETURNS TRIGGER AS $$
DECLARE
    v_user_id UUID;
    v_other_user_id UUID;
    v_unread_count INTEGER;
BEGIN
    -- Get the user who is reading (not the sender)
    IF NEW.is_read = true AND OLD.is_read = false THEN
        -- Find the other user in the conversation
        SELECT 
            CASE 
                WHEN m.user1_id = NEW.sender_id THEN m.user2_id
                ELSE m.user1_id
            END INTO v_other_user_id
        FROM public.matches m
        WHERE m.id = NEW.match_id;

        v_user_id := v_other_user_id;

        -- Count remaining unread messages
        SELECT COUNT(*) INTO v_unread_count
        FROM public.messages
        WHERE match_id = NEW.match_id
        AND sender_id != v_user_id
        AND is_read = false
        AND is_deleted = false;

        -- Update or insert read state
        INSERT INTO public.conversation_read_state 
            (user_id, match_id, last_read_message_id, last_read_time, unread_count)
        VALUES (v_user_id, NEW.match_id, NEW.id, NOW(), v_unread_count)
        ON CONFLICT (user_id, match_id) 
        DO UPDATE SET
            last_read_message_id = EXCLUDED.last_read_message_id,
            last_read_time = EXCLUDED.last_read_time,
            unread_count = EXCLUDED.unread_count,
            updated_at = NOW();
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_conversation_read_state
    AFTER UPDATE OF is_read ON public.messages
    FOR EACH ROW
    EXECUTE FUNCTION update_conversation_read_state();

-- Trigger to update user session state
CREATE OR REPLACE FUNCTION update_user_session_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.user_session_state (user_id, updated_at)
    VALUES (NEW.user_id, NOW())
    ON CONFLICT (user_id) 
    DO UPDATE SET
        updated_at = EXCLUDED.updated_at;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_user_session
    AFTER INSERT OR UPDATE ON public.conversation_read_state
    FOR EACH ROW
    EXECUTE FUNCTION update_user_session_timestamp();

-- =====================================================
-- REFRESH AND SYNC FUNCTIONS
-- =====================================================

-- Function to get all conversations that need refresh
CREATE OR REPLACE FUNCTION get_conversations_needing_refresh(
    p_user_id UUID,
    p_last_refresh_time TIMESTAMPTZ DEFAULT NULL
)
RETURNS TABLE (
    match_id UUID,
    other_user_id UUID,
    other_user_name TEXT,
    last_message_time TIMESTAMPTZ,
    last_read_time TIMESTAMPTZ,
    unread_count INTEGER,
    needs_refresh BOOLEAN
) AS $$
BEGIN
    -- If no last refresh time, use the user's last check time
    IF p_last_refresh_time IS NULL THEN
        SELECT COALESCE(messages_viewed_at, NOW() - INTERVAL '1 day')
        INTO p_last_refresh_time
        FROM public.user_session_state
        WHERE user_id = p_user_id;

        IF p_last_refresh_time IS NULL THEN
            p_last_refresh_time := NOW() - INTERVAL '1 day';
        END IF;
    END IF;

    RETURN QUERY
    SELECT 
        m.id as match_id,
        CASE 
            WHEN m.user1_id = p_user_id THEN m.user2_id 
            ELSE m.user1_id 
        END as other_user_id,
        CASE 
            WHEN m.user1_id = p_user_id THEN p2.name 
            ELSE p1.name 
        END as other_user_name,
        COALESCE(m.last_message_at, m.created_at) as last_message_time,
        COALESCE(crs.last_read_time, m.created_at) as last_read_time,
        COALESCE(crs.unread_count, 0) as unread_count,
        CASE 
            WHEN m.last_message_at > p_last_refresh_time THEN true
            WHEN crs.updated_at > p_last_refresh_time THEN true
            ELSE false
        END as needs_refresh
    FROM public.matches m
    LEFT JOIN public.profiles p1 ON m.user1_id = p1.id
    LEFT JOIN public.profiles p2 ON m.user2_id = p2.id
    LEFT JOIN public.conversation_read_state crs ON 
        crs.user_id = p_user_id AND crs.match_id = m.id
    WHERE (m.user1_id = p_user_id OR m.user2_id = p_user_id)
    AND (
        m.last_message_at > p_last_refresh_time
        OR crs.updated_at > p_last_refresh_time
        OR crs.last_read_time IS NULL
    )
    ORDER BY COALESCE(m.last_message_at, m.created_at) DESC;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to sync messages for a conversation
CREATE OR REPLACE FUNCTION sync_conversation_messages(
    p_user_id UUID,
    p_match_id UUID,
    p_last_sync_time TIMESTAMPTZ DEFAULT NULL
)
RETURNS TABLE (
    sync_completed BOOLEAN,
    messages_found INTEGER,
    new_messages INTEGER,
    updated_messages INTEGER,
    sync_time TIMESTAMPTZ
) AS $$
DECLARE
    v_messages_found INTEGER;
    v_new_messages INTEGER;
    v_updated_messages INTEGER;
    v_sync_time TIMESTAMPTZ := NOW();
BEGIN
    -- Record sync start
    INSERT INTO public.message_sync_log 
        (user_id, match_id, sync_type, sync_status, sync_start_time)
    VALUES (p_user_id, p_match_id, 'incremental', 'pending', v_sync_time);

    -- If no last sync time, get from conversation read state
    IF p_last_sync_time IS NULL THEN
        SELECT COALESCE(last_read_time, NOW() - INTERVAL '30 days')
        INTO p_last_sync_time
        FROM public.conversation_read_state
        WHERE user_id = p_user_id AND match_id = p_match_id;

        IF p_last_sync_time IS NULL THEN
            p_last_sync_time := NOW() - INTERVAL '30 days';
        END IF;
    END IF;

    -- Count messages found
    SELECT COUNT(*) INTO v_messages_found
    FROM public.messages
    WHERE match_id = p_match_id
    AND created_at > p_last_sync_time;

    -- Count new messages (unread)
    SELECT COUNT(*) INTO v_new_messages
    FROM public.messages
    WHERE match_id = p_match_id
    AND sender_id != p_user_id
    AND created_at > p_last_sync_time
    AND is_read = false;

    -- Count updated messages (edited or read status changed)
    SELECT COUNT(*) INTO v_updated_messages
    FROM public.messages
    WHERE match_id = p_match_id
    AND updated_at > p_last_sync_time
    AND created_at <= p_last_sync_time;

    -- Update sync log
    UPDATE public.message_sync_log
    SET sync_status = 'completed',
        sync_end_time = v_sync_time,
        messages_synced = v_messages_found
    WHERE user_id = p_user_id 
    AND match_id = p_match_id 
    AND sync_start_time = v_sync_time;

    -- Update user's last check time
    UPDATE public.user_session_state
    SET messages_viewed_at = v_sync_time,
        last_conversation_id = p_match_id
    WHERE user_id = p_user_id;

    RETURN QUERY SELECT true, v_messages_found, v_new_messages, v_updated_messages, v_sync_time;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to perform full refresh of all user conversations
CREATE OR REPLACE FUNCTION refresh_all_conversations(
    p_user_id UUID
)
RETURNS TABLE (
    refresh_completed BOOLEAN,
    conversations_updated INTEGER,
    total_new_messages INTEGER,
    refresh_time TIMESTAMPTZ
) AS $$
DECLARE
    v_conversations_updated INTEGER := 0;
    v_total_new_messages INTEGER := 0;
    v_refresh_time TIMESTAMPTZ := NOW();
    v_conversation RECORD;
BEGIN
    -- Record sync start
    INSERT INTO public.message_sync_log 
        (user_id, match_id, sync_type, sync_status, sync_start_time)
    VALUES (p_user_id, NULL, 'full', 'pending', v_refresh_time);

    -- Process each conversation
    FOR v_conversation IN 
        SELECT match_id 
        FROM get_conversations_needing_refresh(p_user_id, NULL)
        WHERE needs_refresh = true
    LOOP
        -- Sync this conversation
        PERFORM sync_conversation_messages(p_user_id, v_conversation.match_id);
        v_conversations_updated := v_conversations_updated + 1;
        
        -- Count new messages in this conversation
        SELECT COUNT(*) INTO v_conversation.new_messages
        FROM public.messages
        WHERE match_id = v_conversation.match_id
        AND sender_id != p_user_id
        AND is_read = false;
        
        v_total_new_messages := v_total_new_messages + v_conversation.new_messages;
    END LOOP;

    -- Update sync log
    UPDATE public.message_sync_log
    SET sync_status = 'completed',
        sync_end_time = v_refresh_time,
        messages_synced = v_total_new_messages
    WHERE user_id = p_user_id 
    AND sync_type = 'full'
    AND sync_start_time = v_refresh_time;

    -- Update user's last refresh time
    UPDATE public.user_session_state
    SET conversations_viewed_at = v_refresh_time,
        updated_at = v_refresh_time
    WHERE user_id = p_user_id;

    RETURN QUERY SELECT true, v_conversations_updated, v_total_new_messages, v_refresh_time;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =====================================================
-- NAVIGATION STATE MANAGEMENT
-- =====================================================

-- Function to handle navigation back to conversations list
CREATE OR REPLACE FUNCTION handle_navigation_to_conversations(
    p_user_id UUID
)
RETURNS TABLE (
    success BOOLEAN,
    conversations_count INTEGER,
    unread_total INTEGER,
    last_refresh_time TIMESTAMPTZ
) AS $$
DECLARE
    v_conversations_count INTEGER;
    v_unread_total INTEGER;
    v_last_refresh_time TIMESTAMPTZ;
BEGIN
    -- Update navigation timestamp
    UPDATE public.user_session_state
    SET conversations_viewed_at = NOW(),
        last_conversation_id = NULL,
        updated_at = NOW()
    WHERE user_id = p_user_id;

    -- Get conversation stats
    SELECT COUNT(*) INTO v_conversations_count
    FROM public.matches
    WHERE user1_id = p_user_id OR user2_id = p_user_id;

    SELECT COALESCE(SUM(unread_count), 0) INTO v_unread_total
    FROM public.conversation_read_state
    WHERE user_id = p_user_id;

    SELECT conversations_viewed_at INTO v_last_refresh_time
    FROM public.user_session_state
    WHERE user_id = p_user_id;

    RETURN QUERY SELECT true, v_conversations_count, v_unread_total, v_last_refresh_time;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to handle navigation to specific conversation
CREATE OR REPLACE FUNCTION handle_navigation_to_conversation(
    p_user_id UUID,
    p_match_id UUID
)
RETURNS TABLE (
    success BOOLEAN,
    conversation_exists BOOLEAN,
    unread_count INTEGER,
    last_message_time TIMESTAMPTZ,
    sync_status TEXT
) AS $$
DECLARE
    v_conversation_exists BOOLEAN;
    v_unread_count INTEGER;
    v_last_message_time TIMESTAMPTZ;
    v_sync_status TEXT;
BEGIN
    -- Check if conversation exists and user has access
    SELECT EXISTS(
        SELECT 1 FROM public.matches 
        WHERE id = p_match_id 
        AND (user1_id = p_user_id OR user2_id = p_user_id)
    ) INTO v_conversation_exists;

    IF NOT v_conversation_exists THEN
        RETURN QUERY SELECT false, false, 0, NULL::TIMESTAMPTZ, 'not_found'::TEXT;
        RETURN;
    END IF;

    -- Update navigation state
    UPDATE public.user_session_state
    SET last_conversation_id = p_match_id,
        updated_at = NOW()
    WHERE user_id = p_user_id;

    -- Get conversation stats
    SELECT unread_count, last_read_time
    INTO v_unread_count, v_last_message_time
    FROM public.conversation_read_state
    WHERE user_id = p_user_id AND match_id = p_match_id;

    IF v_unread_count IS NULL THEN
        v_unread_count := 0;
    END IF;

    -- Get sync status
    SELECT sync_status INTO v_sync_status
    FROM public.message_sync_log
    WHERE user_id = p_user_id AND match_id = p_match_id
    ORDER BY sync_start_time DESC
    LIMIT 1;

    IF v_sync_status IS NULL THEN
        v_sync_status := 'never_synced';
    END IF;

    RETURN QUERY SELECT true, true, v_unread_count, v_last_message_time, v_sync_status;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =====================================================
-- BROWSER REFRESH HANDLING
-- =====================================================

-- Function to handle browser refresh - restore conversation state
CREATE OR REPLACE FUNCTION handle_browser_refresh(
    p_user_id UUID,
    p_current_url TEXT DEFAULT NULL
)
RETURNS TABLE (
    refresh_handled BOOLEAN,
    should_sync_conversations BOOLEAN,
    last_conversation_id UUID,
    conversations_outdated BOOLEAN,
    messages_outdated BOOLEAN
) AS $$
DECLARE
    v_last_conversation_id UUID;
    v_last_refresh_time TIMESTAMPTZ;
    v_conversations_outdated BOOLEAN := false;
    v_messages_outdated BOOLEAN := false;
    v_should_sync BOOLEAN := false;
BEGIN
    -- Get user's last session state
    SELECT last_conversation_id, conversations_viewed_at, messages_viewed_at
    INTO v_last_conversation_id, v_last_refresh_time, v_last_refresh_time
    FROM public.user_session_state
    WHERE user_id = p_user_id;

    IF v_last_conversation_id IS NULL THEN
        v_last_conversation_id := NULL;
    END IF;

    -- Check if conversations are outdated (older than 5 minutes)
    IF v_last_refresh_time IS NULL OR v_last_refresh_time < NOW() - INTERVAL '5 minutes' THEN
        v_conversations_outdated := true;
        v_should_sync := true;
    END IF;

    -- Check if messages are outdated (older than 1 minute)
    IF v_last_refresh_time IS NULL OR v_last_refresh_time < NOW() - INTERVAL '1 minute' THEN
        v_messages_outdated := true;
    END IF;

    -- Update refresh timestamp
    UPDATE public.user_session_state
    SET updated_at = NOW()
    WHERE user_id = p_user_id;

    RETURN QUERY SELECT true, v_should_sync, v_last_conversation_id, v_conversations_outdated, v_messages_outdated;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to restore conversation after page reload
CREATE OR REPLACE FUNCTION restore_conversation_after_reload(
    p_user_id UUID,
    p_match_id UUID
)
RETURNS TABLE (
    restore_success BOOLEAN,
    conversation_data JSONB,
    messages JSONB[],
    unread_count INTEGER,
    last_read_message_id BIGINT
) AS $$
DECLARE
    v_conversation_data JSONB;
    v_messages JSONB[];
    v_unread_count INTEGER;
    v_last_read_message_id BIGINT;
BEGIN
    -- Verify user has access to conversation
    IF NOT EXISTS(
        SELECT 1 FROM public.matches 
        WHERE id = p_match_id 
        AND (user1_id = p_user_id OR user2_id = p_user_id)
    ) THEN
        RETURN QUERY SELECT false, NULL::JSONB, NULL::JSONB[], 0, 0::BIGINT;
        RETURN;
    END IF;

    -- Get conversation data
    SELECT jsonb_build_object(
        'match_id', m.id,
        'other_user_id', CASE WHEN m.user1_id = p_user_id THEN m.user2_id ELSE m.user1_id END,
        'other_user_name', CASE WHEN m.user1_id = p_user_id THEN p2.name ELSE p1.name END,
        'other_user_photos', CASE WHEN m.user1_id = p_user_id THEN p2.photos ELSE p1.photos END,
        'last_message_at', m.last_message_at,
        'created_at', m.created_at
    ) INTO v_conversation_data
    FROM public.matches m
    LEFT JOIN public.profiles p1 ON m.user1_id = p1.id
    LEFT JOIN public.profiles p2 ON m.user2_id = p2.id
    WHERE m.id = p_match_id;

    -- Get recent messages (last 50)
    SELECT array_agg(to_jsonb(msg.*)) INTO v_messages
    FROM (
        SELECT 
            id, sender_id, content, type, is_read, is_edited, created_at
        FROM public.messages
        WHERE match_id = p_match_id
        AND is_deleted = false
        ORDER BY created_at DESC
        LIMIT 50
    ) msg;

    -- Get read state
    SELECT unread_count, last_read_message_id
    INTO v_unread_count, v_last_read_message_id
    FROM public.conversation_read_state
    WHERE user_id = p_user_id AND match_id = p_match_id;

    IF v_unread_count IS NULL THEN
        v_unread_count := 0;
    END IF;

    IF v_last_read_message_id IS NULL THEN
        v_last_read_message_id := 0;
    END IF;

    RETURN QUERY SELECT true, v_conversation_data, v_messages, v_unread_count, v_last_read_message_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =====================================================
-- TESTING QUERIES
-- =====================================================

-- Test session state management
/*
-- Create or update session state
INSERT INTO public.user_session_state (user_id, last_conversation_id, session_active)
VALUES ('user-uuid-here', 'match-uuid-here', true)
ON CONFLICT (user_id) 
DO UPDATE SET last_conversation_id = EXCLUDED.last_conversation_id;
*/

-- Test navigation handling
/*
SELECT * FROM handle_navigation_to_conversations('user-uuid-here');
SELECT * FROM handle_navigation_to_conversation('user-uuid-here', 'match-uuid-here');
*/

-- Test refresh handling
/*
SELECT * FROM handle_browser_refresh('user-uuid-here', 'http://localhost:5173/chat');
*/

-- Test conversation restoration
/*
SELECT * FROM restore_conversation_after_reload('user-uuid-here', 'match-uuid-here');
*/

-- Test sync functions
/*
SELECT * FROM sync_conversation_messages('user-uuid-here', 'match-uuid-here');
SELECT * FROM refresh_all_conversations('user-uuid-here');
*/

-- =====================================================
-- MONITORING QUERIES
-- =====================================================

-- Check sync status for all users
SELECT 
    uss.user_id,
    p.name as user_name,
    uss.session_active,
    uss.conversations_viewed_at,
    uss.messages_viewed_at,
    uss.last_conversation_id,
    COUNT(crs.match_id) as tracked_conversations
FROM public.user_session_state uss
JOIN public.profiles p ON uss.user_id = p.id
LEFT JOIN public.conversation_read_state crs ON uss.user_id = crs.user_id
GROUP BY uss.user_id, p.name, uss.session_active, uss.conversations_viewed_at, uss.messages_viewed_at, uss.last_conversation_id
ORDER BY uss.updated_at DESC;

-- Check sync performance
SELECT 
    user_id,
    sync_type,
    COUNT(*) as sync_count,
    AVG(EXTRACT(EPOCH FROM (sync_end_time - sync_start_time))) as avg_sync_time_seconds,
    SUM(messages_synced) as total_messages_synced,
    COUNT(CASE WHEN sync_status = 'failed' THEN 1 END) as failed_syncs
FROM public.message_sync_log
WHERE sync_start_time > NOW() - INTERVAL '24 hours'
GROUP BY user_id, sync_type
ORDER BY sync_count DESC;

-- Check for stale sessions (inactive for more than 30 minutes)
SELECT 
    user_id,
    session_active,
    updated_at,
    NOW() - updated_at as time_since_last_activity
FROM public.user_session_state
WHERE updated_at < NOW() - INTERVAL '30 minutes'
AND session_active = true;

-- Check conversation read state coverage
SELECT 
    p.id as user_id,
    p.name as user_name,
    COUNT(m.id) as total_conversations,
    COUNT(crs.match_id) as conversations_with_read_state,
    COUNT(m.id) - COUNT(crs.match_id) as missing_read_state
FROM public.profiles p
JOIN public.matches m ON p.id = m.user1_id OR p.id = m.user2_id
LEFT JOIN public.conversation_read_state crs ON p.id = crs.user_id AND m.id = crs.match_id
GROUP BY p.id, p.name
HAVING COUNT(m.id) > COUNT(crs.match_id)
ORDER BY missing_read_state DESC;