
-- ====================================================================
-- UPENDO DATABASE SETUP SCRIPT
-- ====================================================================
-- This script will create all necessary tables, triggers, functions,
-- and security policies for the Upendo application. It is designed
-- to be run on a fresh database to set up the entire schema.
--
-- For future migrations, this file is your single source of truth.
-- ====================================================================

-- ====================================================================
-- STEP 1: CREATE TABLES
-- ====================================================================
-- Note: Table creation logic is inferred from the application code.
-- You may need to adjust data types based on your new database provider.

CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT,
    date_of_birth DATE,
    gender TEXT,
    looking_for TEXT,
    tribe TEXT,
    interests TEXT[],
    location JSONB,
    photos TEXT[],
    bio TEXT,
    occupation TEXT,
    education TEXT,
    height TEXT,
    drinking TEXT,
    smoking TEXT,
    religion TEXT,
    firstDate TEXT,
    loveLanguage TEXT,
    subscription TEXT DEFAULT 'free',
    isVerified BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user1_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    user2_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id BIGINT NOT NULL REFERENCES public.matches(id) ON DELETE CASCADE,
    sender_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    content TEXT,
    type TEXT DEFAULT 'text',
    is_read BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.swipes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    swiper_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    swiped_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    direction TEXT, -- 'left' or 'right'
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.stories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    image_url TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- ====================================================================
-- STEP 2: SETUP AUTH TRIGGER FOR NEW USERS
-- ====================================================================
-- This function automatically creates a profile entry when a new user signs up.

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id)
  VALUES (new.id);
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


-- ====================================================================
-- STEP 3: SETUP ROW LEVEL SECURITY (RLS)
-- ====================================================================

-- Enable RLS for all relevant tables
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.matches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.swipes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stories ENABLE ROW LEVEL SECURITY;

-- --- PROFILES TABLE POLICIES ---
CREATE POLICY "Users can view their own profile" ON public.profiles
FOR SELECT USING (auth.uid() = id);

CREATE POLICY "Users can update their own profile" ON public.profiles
FOR UPDATE USING (auth.uid() = id) WITH CHECK (auth.uid() = id);


-- --- STORAGE (AVATARS) POLICIES ---
-- Note: These policies apply to the `storage.objects` table, not a user table.
CREATE POLICY "Allow authenticated uploads to avatars" ON storage.objects
FOR INSERT WITH CHECK ((bucket_id = 'avatars') AND (auth.role() = 'authenticated'));

CREATE POLICY "Allow authenticated view of own photos in avatars" ON storage.objects
FOR SELECT USING ((bucket_id = 'avatars') AND (auth.uid() = owner));

CREATE POLICY "Allow authenticated update of own photos in avatars" ON storage.objects
FOR UPDATE USING ((bucket_id = 'avatars') AND (auth.uid() = owner));

CREATE POLICY "Allow authenticated delete of own photos in avatars" ON storage.objects
FOR DELETE USING ((bucket_id = 'avatars') AND (auth.uid() = owner));

-- Add policies for other tables as needed for your application logic.
-- Example:
-- CREATE POLICY "Users can see their own matches" ON public.matches
-- FOR SELECT USING (auth.uid() = user1_id OR auth.uid() = user2_id);


-- ====================================================================
-- STEP 4: (OPTIONAL) HELPER FUNCTIONS
-- ====================================================================
-- This function was used for debugging and may not be needed, but is included for completeness.

CREATE OR REPLACE FUNCTION public.update_user_profile(update_data jsonb)
RETURNS void AS $$
BEGIN
  UPDATE public.profiles
  SET
    bio = COALESCE(update_data->>'bio', bio),
    occupation = COALESCE(update_data->>'occupation', occupation),
    education = COALESCE(update_data->>'education', education),
    height = COALESCE(update_data->>'height', height),
    drinking = COALESCE(update_data->>'drinking', drinking),
    smoking = COALESCE(update_data->>'smoking', smoking),
    religion = COALESCE(update_data->>'religion', religion),
    firstDate = COALESCE(update_data->>'firstDate', firstDate),
    loveLanguage = COALESCE(update_data->>'loveLanguage', loveLanguage)
  WHERE id = auth.uid();
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ====================================================================
-- END OF SCRIPT
-- ====================================================================

