-- Create message_requests table for managing user-to-user message requests
CREATE TABLE IF NOT EXISTS public.message_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    receiver_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'declined')),
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Add unique constraint to prevent duplicate message requests
ALTER TABLE public.message_requests
ADD CONSTRAINT unique_message_request UNIQUE (sender_id, receiver_id);

-- Create indexes for faster queries
CREATE INDEX IF NOT EXISTS idx_message_requests_sender_id ON public.message_requests(sender_id);
CREATE INDEX IF NOT EXISTS idx_message_requests_receiver_id ON public.message_requests(receiver_id);
CREATE INDEX IF NOT EXISTS idx_message_requests_status ON public.message_requests(status);
CREATE INDEX IF NOT EXISTS idx_message_requests_created_at ON public.message_requests(created_at);

-- Enable RLS
ALTER TABLE public.message_requests ENABLE ROW LEVEL SECURITY;

-- Create RLS policies
CREATE POLICY "Users can insert their own message requests"
ON public.message_requests
FOR INSERT WITH CHECK (auth.uid() = sender_id);

CREATE POLICY "Users can view message requests sent to them"
ON public.message_requests
FOR SELECT USING (auth.uid() = receiver_id OR auth.uid() = sender_id);

CREATE POLICY "Users can update message requests sent to them"
ON public.message_requests
FOR UPDATE USING (auth.uid() = receiver_id);

CREATE POLICY "Users can delete their own message requests"
ON public.message_requests
FOR DELETE USING (auth.uid() = sender_id);

-- Create function to automatically update updated_at timestamp if it doesn't exist
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger for updated_at
CREATE TRIGGER update_message_requests_updated_at
    BEFORE UPDATE ON public.message_requests
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();