CREATE TABLE public.word_filter (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  word TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

ALTER TABLE public.word_filter ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow authenticated users to read" ON public.word_filter FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow admin users to manage" ON public.word_filter FOR ALL USING (auth.jwt()->>'role' = 'admin') WITH CHECK (auth.jwt()->>'role' = 'admin');