-- Create flagged_content table
CREATE TABLE IF NOT EXISTS public.flagged_content (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  word_id BIGINT REFERENCES public.word_filter(id) ON DELETE CASCADE NOT NULL,
  content TEXT NOT NULL,
  context TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

ALTER TABLE public.flagged_content ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow admin users to manage" ON public.flagged_content FOR ALL USING (auth.jwt()->>'role' = 'admin') WITH CHECK (auth.jwt()->>'role' = 'admin');