-- supabase/migrations/20260422150000_create_dislikes_table.sql
CREATE TABLE dislikes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    disliked_user_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Add a unique constraint to prevent duplicate dislikes
ALTER TABLE dislikes
ADD CONSTRAINT unique_dislike UNIQUE (user_id, disliked_user_id);

-- Create indexes for faster queries
CREATE INDEX idx_dislikes_user_id ON dislikes(user_id);
CREATE INDEX idx_dislikes_disliked_user_id ON dislikes(disliked_user_id);

-- Enable RLS
ALTER TABLE dislikes ENABLE ROW LEVEL SECURITY;

-- Create RLS policies
CREATE POLICY "Users can insert their own dislikes"
ON dislikes
FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can view their own dislikes"
ON dislikes
FOR SELECT USING (auth.uid() = user_id);
