CREATE TYPE user_action_type AS ENUM ('warning', 'suspension', 'ban');

CREATE TABLE public.user_actions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    action_type user_action_type NOT NULL,
    reason TEXT,
    admin_id UUID REFERENCES public.profiles(id), -- The admin who took the action
    expires_at TIMESTAMPTZ, -- For suspensions
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

ALTER TABLE public.user_actions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins can manage actions" ON public.user_actions FOR ALL
USING (auth.jwt()->>'role' = 'admin') WITH CHECK (auth.jwt()->>'role' = 'admin');

CREATE POLICY "Users can view their own actions" ON public.user_actions FOR SELECT
USING (auth.uid() = user_id);