CREATE TABLE public.word_actions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  word_id BIGINT REFERENCES public.word_filter(id) ON DELETE CASCADE NOT NULL UNIQUE,
  action_type user_action_type NOT NULL,
  duration_days INT
);

ALTER TABLE public.word_actions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow admin users to manage" ON public.word_actions FOR ALL
USING (is_admin()) WITH CHECK (is_admin());