DROP TABLE IF EXISTS public.word_actions CASCADE;
DROP TABLE IF EXISTS public.system_messages CASCADE;
DROP TABLE IF EXISTS public.user_actions CASCADE;
DROP TABLE IF EXISTS public.flagged_content CASCADE;
DROP TABLE IF EXISTS public.word_filter CASCADE;
DROP TYPE IF EXISTS public.user_action_type CASCADE;
DROP FUNCTION IF EXISTS public.is_admin() CASCADE;
DROP FUNCTION IF EXISTS public.check_content_for_filtered_words() CASCADE;
DROP FUNCTION IF EXISTS public.check_message_for_filtered_words() CASCADE;

CREATE TABLE public.word_filter (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  word TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.flagged_content (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  content TEXT NOT NULL,
  context TEXT NOT NULL,
  word_id BIGINT REFERENCES public.word_filter(id) ON DELETE CASCADE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TYPE user_action_type AS ENUM ('warning', 'suspension', 'ban');

CREATE TABLE public.user_actions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  action_type user_action_type NOT NULL,
  reason TEXT,
  admin_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  expires_at TIMESTAMPTZ,
  status TEXT DEFAULT 'active',
  appeal_reason TEXT
);

CREATE TABLE public.word_actions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  word_id BIGINT REFERENCES public.word_filter(id) ON DELETE CASCADE NOT NULL UNIQUE,
  action_type user_action_type NOT NULL,
  duration_days INT
);

CREATE TABLE public.system_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  message TEXT NOT NULL,
  photo_url TEXT,
  send_as_notification BOOLEAN DEFAULT TRUE,
  send_as_story BOOLEAN DEFAULT FALSE,
  send_as_message BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.word_filter ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.flagged_content ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_actions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.word_actions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.system_messages ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION is_admin()
RETURNS BOOLEAN AS $$
BEGIN
    RETURN (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin';
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP POLICY IF EXISTS "Allow individual insert access" ON public.profiles;
CREATE POLICY "Allow insert for users or admins" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id OR is_admin());
CREATE POLICY "Allow individual read access" ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Allow individual update access" ON public.profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Allow admin read access" ON public.profiles FOR SELECT USING (is_admin());
CREATE POLICY "Allow admin update access" ON public.profiles FOR UPDATE USING (is_admin());

CREATE POLICY "Allow admin users to manage" ON public.word_filter FOR ALL USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY "Allow admin users to read" ON public.flagged_content FOR SELECT USING (is_admin());
CREATE POLICY "Admins can manage actions" ON public.user_actions FOR ALL USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY "Admins can manage system messages" ON public.system_messages FOR ALL USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY "Allow admin users to manage" ON public.word_actions FOR ALL USING (is_admin()) WITH CHECK (is_admin());

CREATE OR REPLACE FUNCTION check_content_for_filtered_words()
RETURNS TRIGGER AS $$
DECLARE
    filtered_word RECORD;
    word_action RECORD;
    expires_at_timestamp TIMESTAMPTZ;
BEGIN
    FOR filtered_word IN SELECT * FROM public.word_filter LOOP
        IF (NEW.bio IS NOT NULL AND NEW.bio ILIKE '%' || filtered_word.word || '%') OR
           (NEW.occupation IS NOT NULL AND NEW.occupation ILIKE '%' || filtered_word.word || '%') OR
           (NEW.education IS NOT NULL AND NEW.education ILIKE '%' || filtered_word.word || '%') OR
           (NEW.religion IS NOT NULL AND NEW.religion ILIKE '%' || filtered_word.word || '%') OR
           (NEW.love_language IS NOT NULL AND NEW.love_language ILIKE '%' || filtered_word.word || '%') OR
           (NEW.drinking IS NOT NULL AND NEW.drinking ILIKE '%' || filtered_word.word || '%') OR
           (NEW.smoking IS NOT NULL AND NEW.smoking ILIKE '%' || filtered_word.word || '%') OR
           (NEW.first_date IS NOT NULL AND NEW.first_date ILIKE '%' || filtered_word.word || '%') THEN

            INSERT INTO public.flagged_content (user_id, content, context, word_id, created_at)
            VALUES (NEW.id,
                    COALESCE(NEW.bio, '') || ' ' ||
                    COALESCE(NEW.occupation, '') || ' ' ||
                    COALESCE(NEW.education, '') || ' ' ||
                    COALESCE(NEW.religion, '') || ' ' ||
                    COALESCE(NEW.love_language, '') || ' ' ||
                    COALESCE(NEW.drinking, '') || ' ' ||
                    COALESCE(NEW.smoking, '') || ' ' ||
                    COALESCE(NEW.first_date, ''),
                    'profile',
                    filtered_word.id,
                    NOW());

            SELECT * INTO word_action FROM public.word_actions WHERE word_id = filtered_word.id;
            IF FOUND THEN
                expires_at_timestamp := NULL;
                IF word_action.action_type = 'suspension' AND word_action.duration_days IS NOT NULL THEN
                    expires_at_timestamp := NOW() + (word_action.duration_days * INTERVAL '1 day');
                END IF;

                INSERT INTO public.user_actions (user_id, action_type, reason, expires_at, status)
                VALUES (NEW.id,
                        word_action.action_type,
                        'Automatic action for using the word: ' || filtered_word.word,
                        expires_at_timestamp,
                        'active');
            END IF;
        END IF;
    END LOOP;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION check_message_for_filtered_words()
RETURNS TRIGGER AS $$
DECLARE
    filtered_word RECORD;
    word_action RECORD;
    expires_at_timestamp TIMESTAMPTZ;
BEGIN
    FOR filtered_word IN SELECT * FROM public.word_filter LOOP
        IF NEW.content ILIKE '%' || filtered_word.word || '%' THEN
            INSERT INTO public.flagged_content (user_id, content, context, word_id, created_at)
            VALUES (NEW.sender_id, NEW.content, 'message', filtered_word.id, NOW());

            SELECT * INTO word_action FROM public.word_actions WHERE word_id = filtered_word.id;
            IF FOUND THEN
                expires_at_timestamp := NULL;
                IF word_action.action_type = 'suspension' AND word_action.duration_days IS NOT NULL THEN
                    expires_at_timestamp := NOW() + (word_action.duration_days * INTERVAL '1 day');
                END IF;

                INSERT INTO public.user_actions (user_id, action_type, reason, expires_at, status)
                VALUES (NEW.sender_id,
                        word_action.action_type,
                        'Automatic action for using the word: ' || filtered_word.word,
                        expires_at_timestamp,
                        'active');
            END IF;
        END IF;
    END LOOP;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER check_profile_for_filtered_words
    AFTER UPDATE ON public.profiles
    FOR EACH ROW
    EXECUTE FUNCTION check_content_for_filtered_words();

CREATE TRIGGER check_message_for_filtered_words
    AFTER INSERT ON public.messages
    FOR EACH ROW
    EXECUTE FUNCTION check_message_for_filtered_words();






