DROP TABLE IF EXISTS public.word_actions CASCADE;
DROP TABLE IF EXISTS public.system_messages CASCADE;
DROP TABLE IF EXISTS public.user_actions CASCADE;
DROP TABLE IF EXISTS public.flagged_content CASCADE;
DROP TABLE IF EXISTS public.word_filter CASCADE;
DROP TYPE IF EXISTS public.user_action_type CASCADE;
DROP FUNCTION IF EXISTS public.is_admin() CASCADE;
DROP FUNCTION IF EXISTS public.check_content_for_filtered_words() CASCADE;
DROP FUNCTION IF EXISTS public.check_message_for_filtered_words() CASCADE;

CREATE TABLE public.word_filter (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  word TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.flagged_content (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  content TEXT NOT NULL,
  context TEXT NOT NULL,
  word_id BIGINT REFERENCES public.word_filter(id) ON DELETE CASCADE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TYPE user_action_type AS ENUM ('warning', 'suspension', 'ban');

CREATE TABLE public.user_actions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  action_type user_action_type NOT NULL,
  reason TEXT,
  admin_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  expires_at TIMESTAMPTZ,
  status TEXT DEFAULT 'active',
  appeal_reason TEXT
);

CREATE TABLE public.word_actions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  word_id BIGINT REFERENCES public.word_filter(id) ON DELETE CASCADE NOT NULL UNIQUE,
  action_type user_action_type NOT NULL,
  duration_days INT
);

CREATE TABLE public.system_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  message TEXT NOT NULL,
  photo_url TEXT,
  send_as_notification BOOLEAN DEFAULT TRUE,
  send_as_story BOOLEAN DEFAULT FALSE,
  send_as_message BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.word_filter ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.flagged_content ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_actions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.word_actions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.system_messages ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION is_admin()
RETURNS BOOLEAN AS $$
BEGIN
    RETURN (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin';
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP POLICY IF EXISTS "Allow individual insert access" ON public.profiles;
CREATE POLICY "Allow insert for users or admins" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id OR is_admin());
CREATE POLICY "Allow individual read access" ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Allow individual update access" ON public.profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Allow admin read access" ON public.profiles FOR SELECT USING (is_admin());
CREATE POLICY "Allow admin update access" ON public.profiles FOR UPDATE USING (is_admin());

CREATE POLICY "Allow admin users to manage" ON public.word_filter FOR ALL USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY "Allow admin users to read" ON public.flagged_content FOR SELECT USING (is_admin());
CREATE POLICY "Admins can manage actions" ON public.user_actions FOR ALL USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY "Admins can manage system messages" ON public.system_messages FOR ALL USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY "Allow admin users to manage" ON public.word_actions FOR ALL USING (is_admin()) WITH CHECK (is_admin());

CREATE OR REPLACE FUNCTION check_content_for_filtered_words()
RETURNS TRIGGER AS $$
DECLARE
    filtered_word RECORD;
    word_action RECORD;
    match_record RECORD;
    other_user_id UUID;
    expires_at_timestamp TIMESTAMPTZ;
BEGIN
    FOR filtered_word IN SELECT * FROM public.word_filter LOOP
        IF (NEW.bio IS NOT NULL AND NEW.bio ILIKE '%' || filtered_word.word || '%') OR
           (NEW.occupation IS NOT NULL AND NEW.occupation ILIKE '%' || filtered_word.word || '%') OR
           (NEW.education IS NOT NULL AND NEW.education ILIKE '%' || filtered_word.word || '%') OR
           (NEW.religion IS NOT NULL AND NEW.religion ILIKE '%' || filtered_word.word || '%') OR
           (NEW.love_language IS NOT NULL AND NEW.love_language ILIKE '%' || filtered_word.word || '%') OR
           (NEW.drinking IS NOT NULL AND NEW.drinking ILIKE '%' || filtered_word.word || '%') OR
           (NEW.smoking IS NOT NULL AND NEW.smoking ILIKE '%' || filtered_word.word || '%') OR
           (NEW.first_date IS NOT NULL AND NEW.first_date ILIKE '%' || filtered_word.word || '%') THEN

            INSERT INTO public.flagged_content (user_id, content, context, word_id, created_at)
            VALUES (NEW.id,
                    COALESCE(NEW.bio, '') || ' ' ||
                    COALESCE(NEW.occupation, '') || ' ' ||
                    COALESCE(NEW.education, '') || ' ' ||
                    COALESCE(NEW.religion, '') || ' ' ||
                    COALESCE(NEW.love_language, '') || ' ' ||
                    COALESCE(NEW.drinking, '') || ' ' ||
                    COALESCE(NEW.smoking, '') || ' ' ||
                    COALESCE(NEW.first_date, ''),
                    'profile',
                    filtered_word.id,
                    NOW());

            SELECT * INTO word_action FROM public.word_actions WHERE word_id = filtered_word.id;
            IF FOUND THEN
                expires_at_timestamp := NULL;
                IF word_action.action_type = 'suspension' AND word_action.duration_days IS NOT NULL THEN
                    expires_at_timestamp := NOW() + (word_action.duration_days * INTERVAL '1 day');
                END IF;

                INSERT INTO public.user_actions (user_id, action_type, reason, expires_at, status)
                VALUES (NEW.id,
                        word_action.action_type,
                        'Automatic action for using the word: ' || filtered_word.word,
                        expires_at_timestamp,
                        'active');
            END IF;
        END IF;
    END LOOP;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION public.check_message_for_filtered_words()
RETURNS TRIGGER AS $$
DECLARE
    filtered_word RECORD;
    word_action RECORD;
    match_record RECORD;
    other_user_id UUID;
    current_strikes INTEGER;
    new_strikes INTEGER;
    notification_message TEXT;
    expires_at_timestamp TIMESTAMPTZ;
BEGIN
    RAISE NOTICE '[TRIGGER] check_message_for_filtered_words started for message content: %s', NEW.content;

    FOR filtered_word IN SELECT * FROM public.word_filter LOOP
        -- Use word boundaries for more accurate matching
        IF NEW.content ~* ('\m' || filtered_word.word || '\m') THEN
            RAISE NOTICE '[TRIGGER] Matched word: "%" in message.', filtered_word.word;

            -- Log the flagged content
            INSERT INTO public.flagged_content (user_id, content, context, word_id)
            VALUES (NEW.sender_id, NEW.content, 'message', filtered_word.id);

            -- Find the corresponding action for this word
            SELECT * INTO word_action FROM public.word_actions WHERE word_id = filtered_word.id;

            -- Proceed only if an action is defined for the word
            IF FOUND THEN
                RAISE NOTICE '[TRIGGER] Action found for word: %s', word_action.action_type;

                -- Find the match to identify the other user for unmatching
                SELECT * INTO match_record FROM public.matches WHERE id = NEW.match_id;

                IF NOT FOUND THEN
                    RAISE NOTICE '[TRIGGER] CRITICAL: Match not found for match_id: %. Aborting action.', NEW.match_id;
                    RETURN NEW; -- Exit trigger if no match is found
                END IF;

                -- Determine the other user's ID
                IF match_record.user1_id = NEW.sender_id THEN
                    other_user_id := match_record.user2_id;
                ELSE
                    other_user_id := match_record.user1_id;
                END IF;

                -- Unmatch the users
                DELETE FROM public.matches WHERE id = NEW.match_id;
                RAISE NOTICE '[TRIGGER] Unmatched users: % and %', NEW.sender_id, other_user_id;

                -- Handle the specific action type
                IF word_action.action_type = 'warning' THEN
                    -- Get current strikes and increment
                    SELECT strikes INTO current_strikes FROM public.profiles WHERE id = NEW.sender_id;
                    new_strikes := COALESCE(current_strikes, 0) + 1;

                    UPDATE public.profiles SET strikes = new_strikes WHERE id = NEW.sender_id;
                    RAISE NOTICE '[TRIGGER] User % strikes updated to: %', NEW.sender_id, new_strikes;

                    -- Create and send notification
                    notification_message := 'You have received a strike for using inappropriate language ("' || filtered_word.word || '"). You now have ' || new_strikes || ' strike(s).';
                    INSERT INTO public.notifications (user_id, type, message) VALUES (NEW.sender_id, 'system', notification_message);

                    -- Check for automatic ban
                    IF new_strikes >= 3 THEN
                        INSERT INTO public.user_actions (user_id, action_type, reason, status) 
                        VALUES (NEW.sender_id, 'ban', 'Automatic ban due to accumulating 3 strikes.', 'active');
                        RAISE NOTICE '[TRIGGER] User % automatically banned.', NEW.sender_id;
                    END IF;

                ELSE -- For 'suspension' or 'ban'
                    expires_at_timestamp := NULL;
                    IF word_action.action_type = 'suspension' AND word_action.duration_days IS NOT NULL THEN
                        expires_at_timestamp := NOW() + (word_action.duration_days * INTERVAL '1 day');
                    END IF;

                    INSERT INTO public.user_actions (user_id, action_type, reason, expires_at, status)
                    VALUES (NEW.sender_id, word_action.action_type, 'Automatic action for using the word: ' || filtered_word.word, expires_at_timestamp, 'active');
                    RAISE NOTICE '[TRIGGER] Action % applied to user %.', word_action.action_type, NEW.sender_id;
                END IF;
                
                -- Since an action was taken, we can stop checking for other words
                RETURN NEW;
            END IF;
        END IF;
    END LOOP;

    RAISE NOTICE '[TRIGGER] No filtered words found in message.';
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER check_profile_for_filtered_words
    AFTER UPDATE ON public.profiles
    FOR EACH ROW
    EXECUTE FUNCTION check_content_for_filtered_words();

CREATE TRIGGER check_message_for_filtered_words
    AFTER INSERT ON public.messages
    FOR EACH ROW
    EXECUTE FUNCTION check_message_for_filtered_words();






