CREATE TABLE public.system_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id UUID REFERENCES public.profiles(id),
    message TEXT NOT NULL,
    photo_url TEXT,
    send_as_notification BOOLEAN DEFAULT TRUE,
    send_as_story BOOLEAN DEFAULT FALSE,
    send_as_message BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

ALTER TABLE public.system_messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins can manage system messages" ON public.system_messages FOR ALL
USING (auth.jwt()->>'role' = 'admin') WITH CHECK (auth.jwt()->>'role' = 'admin');

CREATE POLICY "Authenticated users can read system messages" ON public.system_messages FOR SELECT
TO authenticated
USING (true);