CREATE TABLE public.flagged_content (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) NOT NULL,
  content TEXT NOT NULL,
  context TEXT, -- e.g., 'bio', 'message', 'profile_prompt'
  word_id BIGINT REFERENCES public.word_filter(id) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

ALTER TABLE public.flagged_content ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow admin users to read" ON public.flagged_content FOR SELECT USING (auth.jwt()->>'role' = 'admin');