-- Create word_actions table
CREATE TABLE IF NOT EXISTS public.word_actions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  word_id BIGINT REFERENCES public.word_filter(id) ON DELETE CASCADE NOT NULL,
  action_type TEXT NOT NULL,
  duration_days INTEGER,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

ALTER TABLE public.word_actions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow authenticated users to read" ON public.word_actions FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow admin users to manage" ON public.word_actions FOR ALL USING (auth.jwt()->>'role' = 'admin') WITH CHECK (auth.jwt()->>'role' = 'admin');