-- supabase/migrations/20260423000000_add_popularity_score_system.sql

-- 1. Add new columns to the profiles table
ALTER TABLE public.profiles
ADD COLUMN IF NOT EXISTS popularity_score NUMERIC(5, 2) DEFAULT 65.00,
ADD COLUMN IF NOT EXISTS last_active_at TIMESTAMPTZ DEFAULT NOW(),
ADD COLUMN IF NOT EXISTS last_message_sent_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS daily_swipe_count INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS last_swipe_count_reset_at TIMESTAMPTZ DEFAULT NOW();

-- 2. Create the profile_views table to log individual views
CREATE TABLE IF NOT EXISTS public.profile_views (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    viewer_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    viewed_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- 3. Create the unmatches table
CREATE TABLE IF NOT EXISTS public.unmatches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unmatcher_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    unmatched_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- 4. Add RLS policies for the new tables
ALTER TABLE public.profile_views ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.unmatches ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can insert their own views" ON public.profile_views FOR INSERT WITH CHECK (auth.uid() = viewer_id);
CREATE POLICY "Users can see who viewed them" ON public.profile_views FOR SELECT USING (auth.uid() = viewed_id);

CREATE POLICY "Users can insert their own unmatches" ON public.unmatches FOR INSERT WITH CHECK (auth.uid() = unmatcher_id);
CREATE POLICY "Users can see their own unmatches" ON public.unmatches FOR SELECT USING (auth.uid() = unmatcher_id OR auth.uid() = unmatched_id);
